### ISSUE TITLE
Test fails due to bad from address.

### ISSUE THREAD

**Issue by ameola** [loganmarchione/docker-postfixrelay#19]
The test Email fails due to the from address not being set correctly. It tries to send it from 'MAILER-DAEMON@domain.com' rather than the correct user. The correct user likely needs to be set as a different config value in order to be set correctly. This doesn't prevent external applications from sending mail through the relay and only impacts the test message.

status=bounced (host smtp.office365.com[52.96.18.2] said: 554 5.2.252 SendAsDenied; xxxx@live.com not allowed to send as MAILER-DAEMON@live.com;

**Comment by loganmarchione** [comment]
Hmmm, I have the following set:
- `TEST_EMAIL=logan@my_domain.com`
- `MYORIGIN=my_domain.com`

 And my email comes to me at `logan@my_domain.com` from `[Alert from Postfix] <root@my_domain.com>`. 

How are you running the container? Are you using docker or podman?

**Comment by iiamLost** [comment]
I have the same issue, I'm relaying through my email address' SMTP server. Some services require the email FROM to be the actual email address. Over on the unraid forums someone has raised this issue with the person who's implemented your docker image as a template for unraid.

https://forums.unraid.net/topic/130953-support-devzwf-postfix-relay/

**Comment by iiamLost** [comment]
I can attempt to. I currently have the template installed pointing at your github repository so in theory I can add template variables in the unraid interface to match what you've added in the image. Just let me know what I need to do.

**Comment by iiamLost** [comment]
I was able to pull the new image and add the variable to the template. Different errors this time..
![image](https://github.com/loganmarchione/docker-postfixrelay/assets/44280439/c7115d69-e709-45c2-9beb-5bd95a96c830)

**Comment by loganmarchione** [comment]
Can you now try `1.4.1-beta2`?

**Comment by iiamLost** [comment]
That worked. I received the test email, awesome!

**Comment by loganmarchione** [comment]
Thanks! No, I think I'm good if you're good.

I'll probably post a version without the beta tag here shortly...

**Comment by iiamLost** [comment]
Just tested it with one of the apps I am using and it worked as well. I will point my docker template back to latest after its updated. Thanks again for your help.

**Comment by loganmarchione** [comment]
Just pushed `1.4.1`.  Thanks again for testing.

@ameola can you test this so I can close this issue?

**Comment by loganmarchione** [comment]
No response, closing this.
