### ISSUE TITLE
Message Size Limit as Env Variable

### ISSUE THREAD

**Issue by tholland15** [loganmarchione/docker-postfixrelay#20]
Would it be possible to expose the message_size_limit as an env var? I have been using this container for a while and it has been working great, but I now need the ability to send messages larger than the 10MB default limit.

```
bash-5.1# postconf -d | grep message_size_limit
message_size_limit = 10240000
```

**Comment by loganmarchione** [comment]
@tholland15  I just pushed `1.4.0` with the `MSG_SIZE` environment variable, can you test?

https://hub.docker.com/r/loganmarchione/docker-postfixrelay/tags

I'm getting inconsistent results inside the container depending on how I check the variable.

```
7ae81f6d3edb:/# postconf -d | grep message_size_limit
message_size_limit = 10240000
7ae81f6d3edb:/# postconf message_size_limit
message_size_limit = 30720000
```

**Comment by tholland15** [comment]
You're awesome! Just sent a 20MB PDF without any issue. Thanks for the incredibly quick turnaround on this!
