### ISSUE TITLE
Docker Health is 'unhealthy'

### ISSUE THREAD

**Issue by miljw002** [loganmarchione/docker-postfixrelay#33]
Hi,

I'm running the most recent release of the docker container, and I don't think it's anything I've done or note done.

The docker container is always showing as unhealthy. Looking at the check it's running, it think it's just trying to do a NC to port 25, but it looks like it's never passing/being successful.

Is this something I've done wrong, or is this a known issue?

James

**Comment by loganmarchione** [comment]
Mine is working, also running the latest `1.4.1` . How are you running it? Are you on Linux or something like Windows?

```
Up About a minute (healthy)
```

**Comment by miljw002** [comment]
I'm running it as a docker container on Unraid.

I'm reasonably new to Unraid, so it could be something I've done or not done.

I can see in the docker build file it's using "nc -z localhost 25 || exit 1" as the health check command.

When the container starts, it's on 'starting' for ages, then eventually goes to 'unhealthy'.

It's working and passing email just fine, it's just the health check is saying there is an issue.

**Comment by loganmarchione** [comment]
I hate to say "it works on my machine", but mine is showing healthy. Can you try running it from your local machine to see if it still shows that error? I don't use Unraid, so I don't know if anything was done when it was implemented as an Unraid application.

**Comment by devzwf** [comment]
i think this should be closed

**Comment by miljw002** [comment]
I know this is closed, but reporting back. The recent change (https://github.com/loganmarchione/docker-postfixrelay/issues/40) fixed it.
