### ISSUE TITLE
Container Perpetual 'unhealthy' State after Upgrading from Docker 25 to Docker 26

### ISSUE THREAD

**Issue by tgbanshee** [loganmarchione/docker-postfixrelay#40]
Just upgraded from Docker 25 to Docker 26.1.2 on both Ubuntu 22 and 24. Both now show a perpetual 'unhealthy' state after startup even though everything seems to be working 100%.

**Comment by loganmarchione** [comment]
I just pushed a new version `1.4.3` that changes the healthcheck to use `netstat`. Try that (fwiw, mine is now showing `healthy`).

**Comment by tgbanshee** [comment]
Looks like the 1.4.3 update has fixed the issue. Thank you!
