### ISSUE TITLE
Add optional FROMNAME parameter

### ISSUE THREAD

**Issue by nnerdmann** [loganmarchione/docker-postfixrelay#47]
It would be great to not only be able to change the mail address of the sender, but also to add a optional parameter to change the name. That would require to change the FROM header to something like this:

Alice <alice@example.com>

instead of this:

alice@example.com

**Comment by nnerdmann** [comment]
I'm not so familiar with git, but it seems I cannot create a branch to propose my code changes. So I will try to post it here so maybe somebody can add it.

```
# Set the "from" address, needed for some SMTP providers
# https://serverfault.com/questions/147921/forcing-the-from-address-when-postfix-relays-over-smtp
if [[ -z "$FROMADDRESS" ]]; then
  printf "# ERROR: FROMADDRESS is undefined, continuing\n"
else
  # Determine the FROM header format based on the presence of FROMNAME
  if [[ -z "$FROMNAME" ]]; then
    FROM_HEADER="$FROMADDRESS"
  else
    FROM_HEADER="$FROMNAME <$FROMADDRESS>"
  fi

  printf "# STATE: Using FROM header: %s\n" "$FROM_HEADER"
  postconf -e "smtp_header_checks = regexp:/etc/postfix/header_checks"
  echo "/^From:.*/ REPLACE From: $FROM_HEADER" | tee /etc/postfix/header_checks > /dev/null
  postconf -e "sender_canonical_maps = regexp:/etc/postfix/sender_canonical_maps"
  echo "/.+/ $FROMADDRESS" | tee /etc/postfix/sender_canonical_maps > /dev/null
fi
```

**Comment by loganmarchione** [comment]
You can [fork my repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) then propose a PR to include your changes. Did you test your changes locally?

 I have found the easiest way to set this up is on the client sending the mail and then Postfix will forward it along. For example, here is what my Synology has setup:
![Screenshot_20240823_154527](https://github.com/user-attachments/assets/0c96f214-0e09-4599-9fb4-6814784f5da4)

And this is the resulting email:
![Screenshot_20240823_154557](https://github.com/user-attachments/assets/06c7bcd5-527a-4fc8-9319-549e5638839c)

**Comment by loganmarchione** [comment]
No response, closing issue.
