### ISSUE TITLE
New Feature: Skip Health Check Logs option

### ISSUE THREAD

**Issue by joel72265** [loganmarchione/docker-postfixrelay#48]
I am using HAproxy (with Health checks enabled). This generates logs every second and quickly uses up the free space. Please have an environment variable that disables logging Health checks for certain hosts (eg. -e IGNORE_HOSTS=192.168.1.X1, 192.168.1.X2)

**Comment by loganmarchione** [comment]
I don't use HAproxy so I'm not familiar with it. Is this something that needs to be changed on the HAproxy side? I can't control how often proxy software is querying a Docker container for its health.

This container only generates Postfix logs to [`stdout`](https://github.com/loganmarchione/docker-postfixrelay/blob/master/entrypoint.sh#L28) when a message is sent or if there are config erros. If it's not doing anything, no logs should be created.

**Comment by joel72265** [comment]
Thank you for your reply.

Let me try to explain better. HAProxy sends commands frequently to postfix to check if the container is alive. These checks show up in Postfix logs. Please excuse my ignorance in how this space gets filled up.
![Uploading postfix08.jpg…]()

**Comment by joel72265** [comment]
Thank you for your reply.

Let me try to explain better. HAProxy sends commands frequently to postfix to check if the container is alive. These checks show up in Postfix logs. Please excuse my ignorance in how this space gets filled up.
![postfix08](https://github.com/user-attachments/assets/9d7ed043-e5db-421f-a7d6-c2c9ac457662)

**Comment by loganmarchione** [comment]
I just pushed [`1.4.6`](https://hub.docker.com/layers/loganmarchione/docker-postfixrelay/1.4.6/images/sha256-011c14762b77c7cc420f7631bedf529973db6ed4a8483253fc4cbd0338d4f612?context=explore) with an env var called `LOG_DISABLE` to disable logging after the startup messages. I didn't see a way to disable logging for a specific host without installing something like `rsyslog` into the container. Let me know how that works (I'm also open to other suggestions if you have code-specific examples).
