### ISSUE TITLE
Contribution Link

### ISSUE THREAD

**Issue by joel72265** [loganmarchione/docker-postfixrelay#50]
Thank you for a wonderful software

Maybe consider having a Support / Contribution section link where users can donate some amount or maybe a 'Buy me a coffee' or something similar. Just a suggestion

**Comment by loganmarchione** [comment]
I appreciate the suggestion but can't accept donations. For this specific project, you should donate to the upstream Postfix developers.

For more, see [here](https://loganmarchione.com/donate).

**Comment by joel72265** [comment]
you are welcome, noted.
