### ISSUE TITLE
Feature Request - Make 'mynetworks' configurable

### ISSUE THREAD

**Issue by ksarnelli** [loganmarchione/docker-postfixrelay#8]
Can you make the 'mynetworks' setting (in /etc/postfix/main.cnf) configurable as an environment variable?  Right now it defaults to 0.0.0.0/0 but I'd like to lock it down to particular hosts.

Thanks!

**Comment by loganmarchione** [comment]
Please test v1.3.0 and let me know.

https://hub.docker.com/r/loganmarchione/docker-postfixrelay/tags

**Comment by ksarnelli** [comment]
> Please test v1.3.0 and let me know.
> 
> https://hub.docker.com/r/loganmarchione/docker-postfixrelay/tags

Works great, thanks for the quick turnaround!

**Comment by loganmarchione** [comment]
🙏
